name: Deploy JAR app to Azure Web App - SpringbootDeploymentMediChain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SpringbootDeploymentMediChain'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CB0E97AAC10442FEA51D1E8DEF816ACF }}
          package: 'path/to/your/jar/file.jar' # Replace this with the path to your JAR file
